### ISSUE TITLE
Can you provide examples of C++ and C#?

### ISSUE THREAD

**Issue by Kerryway** [microsoft/IPC#23]
Can you provide examples of C++ and C#?The test is too simpler，i don't know how to use it

**Comment by dtamade** [comment]
me too.

**Comment by carun** [comment]
@Kerryway If you don't need the C# wrapper, [boost::interprocess](https://www.boost.org/doc/libs/1_69_0/doc/html/interprocess.html) is much easier to use than this library. Give it a shot.
